# NumPy Exercises
---
**In this assignment we are going to do some basic coding exercises using NumPy.**

## Setup

### Google Colab

This *should* run with no issues or special setup within Google Colab.

### Local Environment

Follow the directions within the `local_environment/SETUP.md`.

Then, make sure to change the ipykernel in the top right of this VS Code window to `dl_hw0`.

#### Imports
When you change the `hw0.py` file, you will likely have to restart the ipykernel to see the effects (the "Restart" prompt near the top of the page). You can mitigate this overhead by looking at either [this SO post for VSCode](https://stackoverflow.com/questions/59757092/have-colab-reload-a-recently-changed-module-on-drive) or [this SO post for Google Colab](https://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython). You still need to reload the cell below, however.

In [1]:
import numpy as np
import hw0

#### Q1: Create a zero vector of size 10

In [2]:
print(hw0.q1())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Q2: Create an int64 zero matrix of size (10, 10) with the diagonal values set to -1

In [3]:
print(hw0.q2())
print(hw0.q2().dtype)

# x0 = np.zeros((10, 10), dtype=np.int64)
# print(x0)
# # x = np.fill_diagonal(x0, -1.)
# x = x0.copy()
# for i in range(10):
#     x[i,i] = -1
# print(x)

[[-1  0  0  0  0  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0  0  0  0]
 [ 0  0  0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0 -1  0  0  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  0  0 -1]]
int64


#### Q3: Create an 8x8 matrix and fill it with a checkerboard pattern with 0s and 1s (starting with 0 at [0, 0])

In [4]:
print(hw0.q3())

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### Q4: Randomly place five 1s in a given zero matrix

In [5]:
x = np.zeros((8, 8))
# print(x)
print(hw0.q4(x))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]]


#### Q5: Channel conventions

Most image data is given in a *channel-last convention*, e.g., an image is represented as a tensor of shape `(224, 224, 3)`, with the last dimension as the RGB channel dimension. In some deep learning frameworks such as PyTorch, however, images are often taken as input in *channel-first convention*. Now you are given a channel-last image tensor `im`. Convert it to a *channel-first* image tensor. In other words, given a tensor (image) of dimensions of (H, W, C), return the same tensor as (C, H, W).

In [6]:
im = np.random.randn(224, 224, 3)
print(im.shape)
print(hw0.q5(im).shape)

(224, 224, 3)
(3, 224, 224)


#### Q6: Color channels
Now, given a tensor (image) of dimension (C, H, W) with channel ordering of RGB, swap the channel ordering to BGR

In [7]:
im = np.random.randint(255, size=(3, 5, 5))
print(im)
print(hw0.q6(im))

# bgr = np.array((im[2,:,:], im[1,:,:], im[0,:,:]))
# print(bgr)

[[[121 183  41 127 223]
  [152  30   8 127 107]
  [217 213 216 162 160]
  [214 217 220  74 181]
  [109 252 139  65 190]]

 [[143  45  36  56 192]
  [124  76 100 241 111]
  [ 73 187  22 207  71]
  [ 33  38 120 187  94]
  [160 205  85 131 185]]

 [[208  47 175 121 222]
  [ 77  29  68 182 144]
  [ 60 171 117  18 125]
  [174 194 179 180 197]
  [147  83  84  56  86]]]
[[[208  47 175 121 222]
  [ 77  29  68 182 144]
  [ 60 171 117  18 125]
  [174 194 179 180 197]
  [147  83  84  56  86]]

 [[143  45  36  56 192]
  [124  76 100 241 111]
  [ 73 187  22 207  71]
  [ 33  38 120 187  94]
  [160 205  85 131 185]]

 [[121 183  41 127 223]
  [152  30   8 127 107]
  [217 213 216 162 160]
  [214 217 220  74 181]
  [109 252 139  65 190]]]


#### Q7: Given a 1D array, negate (i.e., multiply by -1) all elements in the index range [3, 8], in-place

In [8]:
x = np.arange(11)
print(x)
print(hw0.q7(x))

# print(np.concatenate((x[:2], -x[2:8], x[8:])))

# print(-x[2:8])

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### Q8: Convert a float64 array to a uint8 array

In [9]:
x = np.zeros(10)
print(x.dtype)
print(hw0.q8(x).dtype)

float64
uint8


#### Q9: Subtract the mean of each row in the matrix (i.e., subtract the mean of row1 from each element in row1 and continue)

In [10]:
x = np.random.randn(3, 5)
print(x)
print(hw0.q9(x))

# x = np.array(([1,2,3],[10,20,30]))
# print(x)
# print(x - np.mean(x, axis=1).reshape(x.shape[0], -1))

[[ 0.71898409  0.11824959  0.01789859 -1.34056675  0.63628414]
 [-2.25174758 -0.9732946  -0.79708733 -1.27911852  0.51448386]
 [ 1.13801652  0.62587831  1.45109204 -0.81442593 -2.02109832]]
[[ 0.68881416  0.08807966 -0.01227134 -1.37073668  0.60611421]
 [-1.29439474 -0.01594177  0.1602655  -0.32176568  1.47183669]
 [ 1.062124    0.54998578  1.37519952 -0.89031845 -2.09699085]]


#### Q10: If you did Q9 with a loop, can you do it without loop?
Just copy Q9 if you already did so without a loop.

In [11]:
x = np.random.randn(3, 5)
print(x)
print(hw0.q10(x))

[[ 0.05930424 -0.38973509  1.08750926  0.08179751 -0.84054001]
 [ 1.31189857  0.8473951  -1.46892341  0.05066439 -1.88882145]
 [ 0.78202644 -0.13357892  0.40894685  0.89381471  0.65329047]]
[[ 0.05963706 -0.38940227  1.08784207  0.08213033 -0.84020719]
 [ 1.54145593  1.07695246 -1.23936605  0.28022176 -1.65926409]
 [ 0.26112653 -0.65447883 -0.11195306  0.3729148   0.13239056]]


#### Q11: Sort the rows of a matrix by the matrix's second column

In [12]:
x = np.random.randint(low=0, high=10, size=(5, 5))
print(x)
# print(x[:,1])
print(hw0.q11(x))

[[3 5 7 8 9]
 [8 6 4 5 3]
 [1 0 2 2 9]
 [5 1 8 4 1]
 [5 6 1 1 9]]
[[1 0 2 2 9]
 [5 1 8 4 1]
 [3 5 7 8 9]
 [8 6 4 5 3]
 [5 6 1 1 9]]


#### Q12: One-hot encoding 
One-hot is a commonly-used representation in Deep Learning. For example, an integer `5` is represented as a size-*N* array where the 5th element is `1` and all other elements are all zeros. For example, if `N=10`, we have:

`[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]`

Convert the following array of size 5 to its one-hot encoding matrix with `N=10`. The result should be a matrix (2D array) of shape `(5, 10)`.

In [13]:
x = np.random.randint(10, size=(5))
print(x)
print(hw0.q12(x))

[7 0 3 5 6]
[7 0 3 5 6]


#### Q13: In a single expression, multiply the n-th row of a given matrix with the n-th element in a given vector

*Hint*: Use array broadcasting

In [14]:
x = np.random.randint(10, size=(5, 5))
y = np.arange(5)
print(x)
print(y)
print(hw0.q13(x, y))

[[3 7 8 1 3]
 [6 4 6 5 8]
 [1 2 4 8 5]
 [9 1 2 6 8]
 [7 6 3 4 2]]
[0 1 2 3 4]
[[3 7 8 1 3]
 [6 4 6 5 8]
 [1 2 4 8 5]
 [9 1 2 6 8]
 [7 6 3 4 2]]


#### Q14: Without using `np.pad`, pad an array with a border of zeros

In [15]:
x = np.ones((4, 4))
print(x)
# print(np.pad(x, 1))
# print(hw0.q14(x))


r, c = x.shape
v = np.zeros((c))
h = np.zeros((r+2))
# print(v, h.T)
# x = np.hstack((h.T, x, h.T))
x = np.vstack((v, x, v))
print(x)
x = np.concatenate((h.T, x, h.T))
print(h, x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)