In [ ]:
#Cell 1
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#Cell 2
%cd /content/drive/MyDrive/'hw1.zip (Unzipped Files)'/hw1/student_version/data # or your custom path
!sh get_data.sh
%cd ..

In [ ]:
# Cell 3
# Run all local tests in this block
# If you get an error saying test not found, add an __init__.py file in the
# tests directory
!python -m unittest tests.test_network

In [1]:
#Cell 4
import yaml
import copy

from models import TwoLayerNet, SoftmaxRegression
from optimizer import SGD
from utils import load_mnist_trainval, load_mnist_test, generate_batched_data, train, evaluate, plot_curves

In [2]:
from utils import load_csv
import numpy as np
import random
data, labels = load_csv('./data/mnist_train.csv')

In [43]:
a = [4,5,6,7]
b = [4,5,6,7]
# random.shuffle(a)
# print(a)
c = [8,8,8,5]
d = [0,0,0,5]

total = [a,b,c,d]
# print(total.pop(3))

data_reduced = data[:100]
labels_reduced = labels[:100]
np.shape(data_reduced)
indices = ['a', 'b', 'c', 'd']

print(total)
print(indices)

# https://stackoverflow.com/questions/23289547/shuffle-two-list-at-once-with-same-order
c = list(zip(total, indices))
random.shuffle(c)

total, indices = zip(*c)
print(total)
print(indices)
# generate_batched_data(data, labels)
# generate_batched_data(data_reduced, labels[:1000])

aa = np.array((0,1,2,3))
bb = np.array((0,1,2,3))
np.where(aa == bb, 1, 0)

1 / (1 + np.exp(-aa))

cc = np.array(((-1, 2), (10, -9)))
np.maximum(0, cc)

[[4, 5, 6, 7], [4, 5, 6, 7], [8, 8, 8, 5], [0, 0, 0, 5]]
['a', 'b', 'c', 'd']
([0, 0, 0, 5], [4, 5, 6, 7], [8, 8, 8, 5], [4, 5, 6, 7])
('d', 'a', 'c', 'b')


array([[ 0,  2],
       [10,  0]])

In [37]:
data_reduced = data[:35]
labels_reduced = labels[:35]

seed = None
shuffle = False
batch_size = 16

batched_data = []
batched_label = []
if seed:
    random.seed(seed)
#############################################################################
# TODO:
#    1) Shuffle data using random.shuffle and label if shuffle=True                              #
#    2) Generate batches of images with the required batch size             #
#    It's okay if the size of your last batch is smaller than the required  #
#    batch size                                                             #
#############################################################################

auxiliary = list(range(len(labels_reduced)))
if shuffle:
    random.shuffle(auxiliary)
    # data_shuffled, label_shuffled = []
    # for i in auxiliary:
    #     data_shuffled.append(data[i])
    #     label_shuffled.append(label[i])

done = False
count = 0
# while not done:

#     # accommodate smaller last batch
#     if len(auxiliary) < batch_size:
#         batch_size = len(auxiliary)

#     # define termination
#     if len(auxiliary) <= 0:
#         done = True 

#     # extract rows to batch
#     batch_of_data, batch_of_label = [], []
#     for i in range(batch_size):
#         print(auxiliary[0])
#         batch_of_data.append(data_reduced.pop(auxiliary[0]))
#         batch_of_label.append(labels_reduced.pop(auxiliary[0]))
#         auxiliary.pop(0)
#         count += 1
#     # append batches
#     print('out of for')
#     batched_data.append(batch_of_data)
#     batched_label.append(batch_of_label)  

if len(labels_reduced) % batch_size == 0.0:
    num_of_batches = len(labels_reduced) / batch_size
else:
    num_of_batches = (len(labels_reduced) / batch_size) + 1

batched_data, batched_label = [], []
idx = 0
for i in range(int(num_of_batches)):
    batched_data.append(data_reduced[idx:idx + batch_size])
    batched_label.append(labels_reduced[idx:idx + batch_size])
    idx += batch_size

print(labels_reduced)
print(batched_label)


[1, 3, 5, 7, 9, 1, 3, 8, 5, 6, 9, 5, 0, 8, 1, 0, 1, 7, 0, 7, 6, 9, 7, 0, 1, 7, 3, 3, 4, 0, 7, 4, 4, 3, 4]
[[1, 3, 5, 7, 9, 1, 3, 8, 5, 6, 9, 5, 0, 8, 1, 0], [1, 7, 0, 7, 6, 9, 7, 0, 1, 7, 3, 3, 4, 0, 7, 4], [4, 3, 4]]


In [53]:
np.shape(batched_data)
print(num_of_batches % 1)

0.0


In [24]:
a = np.array((0,1,2))

s = np.exp(a) / np.sum(np.exp(a))

-np.log(s)

array([2.40760596, 1.40760596, 0.40760596])

In [126]:
# # x = np.array([[-1.48839468, -0.31530738],
# #                 [-0.28271176, -1.00780433],
# #                 [0.66435418, 1.2537461],
# #                 [-1.64829182, 0.90223236]])
# # y = np.array([[0.23629739, 0.76370261],
# #                 [0.67372745, 0.32627255],
# #                 [0.35677439, 0.64322561],
# #                 [0.07239128, 0.92760872]])
# # # print(max(x))
# # print(np.exp(x - np.max(x)) / np.sum(np.exp(x - np.max(x))) )
# # # # print(np.exp(y) / np.sum(np.exp(y)))


x_pred = np.array([[0.2, 0.5, 0.3], [0.5, 0.1, 0.4], [0.3, 0.3, 0.4]])
y = np.array([1, 2, 0])
expected_loss = 0.937803


# print(-y * np.log(x_pred))

pred_classes = np.argmax(x_pred, axis=1)
# print(pred_classes)
y_vals = x_pred[:, y]

loss = -np.sum(y * np.log(np.max(x_pred[pred_classes])))

# print(loss)

def softmax_(x):
    return np.exp(x) / np.sum(np.exp(x))

ss = softmax_([0.5, 0.5, 0.4])

manual_loss = -( 1*np.log(ss[0]) + 2*np.log(ss[1]) + 0*np.log(ss[2]) )

# # # print(-np.sum(np.log(x_pred[np.arange(3), y]))/3)

# print(x_pred)

pred_probs = []
for i in range(len(y)):
    pred_probs.append(x_pred[i, y[i]])
pred_probs = np.array(pred_probs)

# # pred_probs = np.zeros_like(y)
# # for i in range(len(y)):
# #     print(i, x_pred[i, y[i]])
# #     pred_probs[i] = x_pred[i, y[i]]

# print(pred_probs)
x_pred[0,0] = 0.8
x_pred[0,1] = 0.1
x_pred[-1,-1] = 0.9
print(x_pred)
print(np.max(x_pred, axis=1))

[[0.8 0.1 0.3]
 [0.5 0.1 0.4]
 [0.3 0.3 0.9]]
[0.8 0.3 0.9]


In [ ]:
# Cell 5
%matplotlib inline
def train_model(yaml_config_file):
  args = {}
  with open(yaml_config_file) as f:
      config = yaml.full_load(f)

  for key in config:
      for k, v in config[key].items():
          args[k] = v
  
  # Prepare MNIST data
  train_data, train_label, val_data, val_label = load_mnist_trainval()
  test_data, test_label = load_mnist_test()

  # Prepare model and optimizer
  if args["type"] == 'SoftmaxRegression':
      model = SoftmaxRegression()
  elif args["type"] == 'TwoLayerNet':
      model = TwoLayerNet(hidden_size=args["hidden_size"])
  optimizer = SGD(learning_rate=args["learning_rate"], reg=args["reg"])
  
  # Training Code
  train_loss_history = []
  train_acc_history = []
  valid_loss_history = []
  valid_acc_history = []
  best_acc = 0.0
  best_model = None
  for epoch in range(args["epochs"]):
      batched_train_data, batched_train_label = generate_batched_data(train_data, train_label, batch_size=args["batch_size"], shuffle=True)
      epoch_loss, epoch_acc = train(epoch, batched_train_data, batched_train_label, model, optimizer, args["debug"])

      train_loss_history.append(epoch_loss)
      train_acc_history.append(epoch_acc)
      # evaluate on test data
      batched_test_data, batched_test_label = generate_batched_data(val_data, val_label, batch_size=args["batch_size"])
      valid_loss, valid_acc = evaluate(batched_test_data, batched_test_label, model, args["debug"])
      if args["debug"]:
          print("* Validation Accuracy: {accuracy:.4f}".format(accuracy=valid_acc))

      valid_loss_history.append(valid_loss)
      valid_acc_history.append(valid_acc)

      if valid_acc > best_acc:
          best_acc = valid_acc
          best_model = copy.deepcopy(model)
  
  #Testing Code
  batched_test_data, batched_test_label = generate_batched_data(test_data, test_label, batch_size=args["batch_size"])
  _, test_acc = evaluate(batched_test_data, batched_test_label, best_model) # test the best model
  if args["debug"]:
      print("Final Accuracy on Test Data: {accuracy:.4f}".format(accuracy=test_acc))
  
  return train_loss_history, train_acc_history, valid_loss_history, valid_acc_history

In [ ]:
# Cell 6
# train softmax model
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_softmax.yaml")

In [ ]:
# Cell 7
# plot results for softmax model
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

In [ ]:
# Cell 8
# train two layer neural network
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_twolayer.yaml")

In [ ]:
# Cell 9
# plot two layer neural network
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

# **Assignment 1 Writeup**

- Name: 
- GT Email:
- GT ID:



## Two Layer Neural Network

# Learning Rates

- Tune the Two Layer Neural Network with various learning rates (while keeping all other hyperparameters constant) by changing the config file.
  - lr = 1
  - lr = 1e-1
  - lr = 1e-2
  - lr = 5e-2


In [ ]:
# Cell 10
# Change lr to 1 in the config file and run this code block
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 11
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

In [ ]:
# Cell 12
# Change lr to 1e-1 in the config file and run this code block
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 13
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

In [ ]:
# Cell 14
# Change lr to 1e-2 in the config file and run this code block
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 15
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

In [ ]:
# Cell 16
# Change lr to 5e-2 in the config file and run this code block
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 17
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

Describe and explain your findings here:

# Regularization

- Tune the Two Layer Neural Network with various regularization coefficients (while keeping all other hyperparameters constant) by changing the config file.
  
  - reg = 1e-1
  - reg = 1e-2
  - reg = 1e-3
  - reg = 1e-4
  - reg = 1


In [ ]:
# Cell 18
# Change reg to 1e-1 in the config file and run this code block
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 19
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

In [ ]:
# Cell 20
# Change reg to 1e-2 in the config file and run this code block
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 21
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

In [ ]:
# Cell 22
# Change reg to 1e-3 in the config file and run this code block
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 23
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

In [ ]:
# Cell 24
# Change reg to 1e-4 in the config file and run this code block
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 25
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

In [ ]:
# Cell 26
# Change reg to 1 in the config file and run this code block
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 27
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

Describe and explain your findings here:

## Hyper-parameter Tuning

You are now free to tune any hyperparameters for better accuracy. In this block type the configuration of your best model and provide a brief explanation of why it works.

In [ ]:
# Cell 28
# hyperparameter tuning
train_loss_history, train_acc_history, valid_loss_history, valid_acc_history = train_model("configs/config_exp.yaml")

In [ ]:
# Cell 29
plot_curves(train_loss_history, train_acc_history, valid_loss_history, valid_acc_history)

In [ ]:
# Cell 30
#To collect submission
!sh collect_submission.sh

Describe and explain your findings here: